# Generated by Django 5.2.7 on 2026-06-30 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0002_callclosure'),
        ('ups', '0002_servicerequest_form_simplification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='type_of_call',
            field=models.CharField(blank=True, choices=[('WARRANTY', 'Warranty'), ('AMC', 'AMC'), ('OUT_OF_WARRANTY', 'Out of Warranty')], max_length=50),
        ),
        migrations.AlterField(
            model_name='callclosure',
            name='customer_signature',
            field=models.TextField(blank=True, verbose_name='Customer Signature (Data URL)'),
        ),
        migrations.AddField(
            model_name='callclosure',
            name='closure_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callclosure',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='callclosure',
            name='customer_mobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='callclosure',
            name='out_of_scope_observations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='callclosure',
            name='ups_operational_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='callclosure',
            name='working_condition_demonstrated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EngineerVisitWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_5_customer_contacted', models.BooleanField(default=False)),
                ('step_5_problem_confirmed', models.BooleanField(default=False)),
                ('step_5_location_confirmed', models.BooleanField(default=False)),
                ('step_5_visit_schedule_confirmed', models.BooleanField(default=False)),
                ('step_5_remarks', models.TextField(blank=True)),
                ('step_5_completed_at', models.DateTimeField(blank=True, null=True)),
                ('step_6_model_number', models.CharField(blank=True, max_length=100)),
                ('step_6_serial_number', models.CharField(blank=True, max_length=100)),
                ('step_6_equipment_photo', models.ImageField(blank=True, null=True, upload_to='workflow/step6/equipment/')),
                ('step_6_model_label_photo', models.ImageField(blank=True, null=True, upload_to='workflow/step6/model-label/')),
                ('step_6_serial_label_photo', models.ImageField(blank=True, null=True, upload_to='workflow/step6/serial-label/')),
                ('step_6_complaint_match_status', models.CharField(blank=True, choices=[('MATCHED', 'Matched'), ('MISMATCHED', 'Mismatched')], max_length=20)),
                ('step_6_completed_at', models.DateTimeField(blank=True, null=True)),
                ('step_7_problem_analysis', models.TextField(blank=True)),
                ('step_7_input_voltage', models.CharField(blank=True, max_length=50)),
                ('step_7_output_voltage', models.CharField(blank=True, max_length=50)),
                ('step_7_earthing_status', models.CharField(blank=True, max_length=100)),
                ('step_7_additional_observations', models.TextField(blank=True)),
                ('step_7_supporting_photo', models.ImageField(blank=True, null=True, upload_to='workflow/step7/supporting/')),
                ('step_7_completed_at', models.DateTimeField(blank=True, null=True)),
                ('step_8_part_decision', models.CharField(blank=True, choices=[('AVAILABLE', 'Part Available'), ('NOT_AVAILABLE', 'Part Not Available')], max_length=20)),
                ('step_8_required_part_details', models.TextField(blank=True)),
                ('step_8_indent_details', models.TextField(blank=True)),
                ('step_8_defective_part_photo', models.ImageField(blank=True, null=True, upload_to='workflow/step8/defective/')),
                ('step_8_remarks', models.TextField(blank=True)),
                ('step_8_completed_at', models.DateTimeField(blank=True, null=True)),
                ('step_9_new_part_name', models.CharField(blank=True, max_length=150)),
                ('step_9_new_part_model_number', models.CharField(blank=True, max_length=100)),
                ('step_9_new_part_serial_number', models.CharField(blank=True, max_length=100)),
                ('step_9_defective_part_model_number', models.CharField(blank=True, max_length=100)),
                ('step_9_defective_part_serial_number', models.CharField(blank=True, max_length=100)),
                ('step_9_replacement_date_time', models.DateTimeField(blank=True, null=True)),
                ('step_9_installed_part_photo', models.ImageField(blank=True, null=True, upload_to='workflow/step9/installed/')),
                ('step_9_defective_part_photo', models.ImageField(blank=True, null=True, upload_to='workflow/step9/defective/')),
                ('step_9_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='ups.servicerequest')),
            ],
            options={
                'verbose_name': 'Engineer Visit Workflow',
                'verbose_name_plural': 'Engineer Visit Workflows',
            },
        ),
    ]
