from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ups", "0003_alter_servicerequest_type_of_call_callclosure_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_5_customer_contacted",
            new_name="step_1_customer_contacted",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_5_problem_confirmed",
            new_name="step_1_problem_confirmed",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_5_location_confirmed",
            new_name="step_1_location_confirmed",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_5_visit_schedule_confirmed",
            new_name="step_1_visit_schedule_confirmed",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_5_remarks",
            new_name="step_1_remarks",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_5_completed_at",
            new_name="step_1_completed_at",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_6_model_number",
            new_name="step_2_model_number",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_6_serial_number",
            new_name="step_2_serial_number",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_6_equipment_photo",
            new_name="step_2_equipment_photo",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_6_model_label_photo",
            new_name="step_2_model_label_photo",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_6_serial_label_photo",
            new_name="step_2_serial_label_photo",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_6_complaint_match_status",
            new_name="step_2_complaint_match_status",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_6_completed_at",
            new_name="step_2_completed_at",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_7_problem_analysis",
            new_name="step_3_problem_analysis",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_7_input_voltage",
            new_name="step_3_input_voltage",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_7_output_voltage",
            new_name="step_3_output_voltage",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_7_earthing_status",
            new_name="step_3_earthing_status",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_7_additional_observations",
            new_name="step_3_additional_observations",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_7_supporting_photo",
            new_name="step_3_supporting_photo",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_7_completed_at",
            new_name="step_3_completed_at",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_8_part_decision",
            new_name="step_4_part_decision",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_8_required_part_details",
            new_name="step_4_required_part_details",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_8_indent_details",
            new_name="step_4_indent_details",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_8_defective_part_photo",
            new_name="step_4_defective_part_photo",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_8_remarks",
            new_name="step_4_remarks",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_8_completed_at",
            new_name="step_4_completed_at",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_9_new_part_name",
            new_name="step_5_new_part_name",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_9_new_part_model_number",
            new_name="step_5_new_part_model_number",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_9_new_part_serial_number",
            new_name="step_5_new_part_serial_number",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_9_defective_part_model_number",
            new_name="step_5_defective_part_model_number",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_9_defective_part_serial_number",
            new_name="step_5_defective_part_serial_number",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_9_replacement_date_time",
            new_name="step_5_replacement_date_time",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_9_installed_part_photo",
            new_name="step_5_installed_part_photo",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_9_defective_part_photo",
            new_name="step_5_defective_part_photo",
        ),
        migrations.RenameField(
            model_name="engineervisitworkflow",
            old_name="step_9_completed_at",
            new_name="step_5_completed_at",
        ),
        migrations.AlterField(
            model_name="engineervisitworkflow",
            name="step_2_equipment_photo",
            field=models.ImageField(blank=True, null=True, upload_to="workflow/step2/equipment/"),
        ),
        migrations.AlterField(
            model_name="engineervisitworkflow",
            name="step_2_model_label_photo",
            field=models.ImageField(blank=True, null=True, upload_to="workflow/step2/model-label/"),
        ),
        migrations.AlterField(
            model_name="engineervisitworkflow",
            name="step_2_serial_label_photo",
            field=models.ImageField(blank=True, null=True, upload_to="workflow/step2/serial-label/"),
        ),
        migrations.AlterField(
            model_name="engineervisitworkflow",
            name="step_3_supporting_photo",
            field=models.ImageField(blank=True, null=True, upload_to="workflow/step3/supporting/"),
        ),
        migrations.AlterField(
            model_name="engineervisitworkflow",
            name="step_4_defective_part_photo",
            field=models.ImageField(blank=True, null=True, upload_to="workflow/step4/defective/"),
        ),
        migrations.AlterField(
            model_name="engineervisitworkflow",
            name="step_5_installed_part_photo",
            field=models.ImageField(blank=True, null=True, upload_to="workflow/step5/installed/"),
        ),
        migrations.AlterField(
            model_name="engineervisitworkflow",
            name="step_5_defective_part_photo",
            field=models.ImageField(blank=True, null=True, upload_to="workflow/step5/defective/"),
        ),
    ]
