# Generated by Django 5.2.7 on 2026-07-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0004_rename_engineer_workflow_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='callclosure',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='callclosure',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callclosure',
            name='out_of_scope_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engineervisitworkflow',
            name='step_1_location_confirmation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='engineervisitworkflow',
            name='step_1_problem_confirmation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='engineervisitworkflow',
            name='step_1_visit_schedule_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engineervisitworkflow',
            name='step_4_replacement_required',
            field=models.BooleanField(default=False),
        ),
    ]
