# Generated by Django 5.2.7 on 2026-07-03 07:06

import django.db.models.deletion
from django.db import migrations, models


def copy_step_3_fields(apps, schema_editor):

    EngineerVisitWorkflow = apps.get_model("ups", "EngineerVisitWorkflow")

    for workflow in EngineerVisitWorkflow.objects.all():
        system_data_lines = []

        if workflow.step_3_input_voltage:
            system_data_lines.append(f"Input Voltage: {workflow.step_3_input_voltage}")

        if workflow.step_3_output_voltage:
            system_data_lines.append(f"Output Voltage: {workflow.step_3_output_voltage}")

        if workflow.step_3_earthing_status:
            system_data_lines.append(f"Earthing Status: {workflow.step_3_earthing_status}")

        workflow.step_3_system_data = "\n".join(system_data_lines)
        workflow.step_3_category_data = []
        workflow.save(update_fields=["step_3_system_data", "step_3_category_data"])


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0005_callclosure_approval_status_callclosure_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineervisitworkflow',
            name='step_3_category_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='engineervisitworkflow',
            name='step_3_system_data',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(copy_step_3_fields, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='engineervisitworkflow',
            name='step_3_earthing_status',
        ),
        migrations.RemoveField(
            model_name='engineervisitworkflow',
            name='step_3_input_voltage',
        ),
        migrations.RemoveField(
            model_name='engineervisitworkflow',
            name='step_3_output_voltage',
        ),
        migrations.CreateModel(
            name='WorkflowAdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('DEFECTIVE', 'Defective Part'), ('REPLACED', 'Replaced Part')], max_length=20)),
                ('image', models.ImageField(upload_to='workflow/additional/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='ups.engineervisitworkflow')),
            ],
            options={
                'verbose_name': 'Workflow Additional Image',
                'verbose_name_plural': 'Workflow Additional Images',
            },
        ),
    ]
