# Generated by Django 5.2.8 on 2026-07-18 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0006_remove_engineervisitworkflow_step_3_earthing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowadditionalimage',
            name='image_type',
            field=models.CharField(choices=[('DEFECTIVE', 'Defective Part'), ('REPLACED', 'Replaced Part'), ('MODEL_SERIAL', 'Model/Serial Label')], max_length=20),
        ),
        migrations.CreateModel(
            name='ClosureAdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='closure/additional/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='ups.callclosure')),
            ],
            options={
                'verbose_name': 'Closure Additional Image',
                'verbose_name_plural': 'Closure Additional Images',
            },
        ),
    ]
